### ISSUE TITLE
Getting a non Json formatted response

### ISSUE THREAD

**Issue by ghost** [0015/ChatGPT_Client_For_Arduino#10]
Hi,

Yesterday my integration with Arduino UNO R4 worked just fine, but today it seems like something is changed in the way the Chat GPT API framework handle the requests\response.
I was getting consistent and pretty neat JSON formatted response, but today this happened:

[ChatGPT] Response: HTTP/1.1 200 OK
Date: Wed, 17 Jul 2024 08:36:42 GMT
Content-Type: application/json
Content-Length: 523
Connection: close
openai-organization: user-[Redacted]
openai-processing-ms: 952
openai-version: 2020-10-01
strict-transport-security: max-age=15552000; includeSubDomains; preload
x-ratelimit-limit-requests: 10000
x-ratelimit-limit-tokens: 10000
x-ratelimit-remaining-requests: 9999
x-ratelimit-remaining-tokens: 9594
x-ratelimit-reset-requests: 8.64s
x-ratelimit-reset-tokens: 2.436s
x-request-id: req_b3096fbb7647b93f6e34613ac64d4e58
CF-Cache-Status: DYNAMIC
Set-Cookie: __cf_bm=3agTzRX30qFrJtYhEkMsZdNAFWzLyIHqp.j78cgrArc-1721205402-1.0.1.1-qGxb2cptvU1RayQk7l62kRkS0VR3.1xGYZllr6u1Ri4CmWVg8PiVllVGc.aPNa8cXn.l2vM4fQOEpgpTt_VoYA; path=/; expires=Wed, 17-Jul-24 09:06:42 GMT; domain=.api.openai.com; HttpOnly; Secure; SameSite=None
X-Content-Type-Options: nosniff
Set-Cookie: _cfuvid=fb2.ZVLMHHsES1VBsSfrnJ4.rnvJWo42ThoWALIBsMg-1721205402822-0.0.1.1-604800000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None
Server: cloudflare
CF-RAY: 8a48e7dfae6abae2-MXP
alt-svc: h3=":443"; ma=86400

Already tried to tweak and change some parameters inside the API Playground \ Chat settings on Open AI side, but nothing is changed.

I only receive partial JSON responses when I intentionally send a bad parameter ( like changing the version of the AI with a wrong one )

EG:

{
    "error": {
        "message": "Cannot specify both model and engine",
        "type": "invalid_request_error",
        "param": null,
        "code": null

BR

Fox

**Comment by 0015** [comment]
@foxbeta90 this is because it was not completed due to lack of memory when constructing the post body. I added a parameter to use static memory in version 0.2.2. I hope you give this a try.

**Comment by ghost** [comment]
Works like a charm :)
Thank you for the quick fix
BR

Fox
