### ISSUE TITLE
I cant run the example

### ISSUE THREAD

**Issue by MrHB17509** [0015/ChatGPT_Client_For_Arduino#2]
`exit status 1

WifiCientSecure.h: no such file or directory` 

Anyone can help me with this?

**Comment by 0015** [comment]
@MrHB17509 Which board are you using?

**Comment by MrHB17509** [comment]
@0015 Arduino Uno

**Comment by 0015** [comment]
@MrHB17509 Which library to use for Internet connection on Arduino Uno? WifiCientSecure is for the ESP32.
Please put the WiFi or Ethernet library you are using into the class type.
ChatGPT< YOUR_COMM_LIBRARY> chat_gpt(&client, "v1", "KEY");
