### ISSUE TITLE
the most of requests are err

### ISSUE THREAD

**Issue by ESPboy-edu** [0015/ChatGPT_Client_For_Arduino#3]
Using ESP8266

the most of requests are return error:
"[ERR] deserializeJson() failed: InvalidInput"

Interestingly, requests of the format: "trip for N days Somewhere" is always processed without errors :)

**Comment by ESPboy-edu** [comment]
```cpp
#include <ArduinoJson.h>
#include <ESP8266WiFi.h>
#include <WiFiClientSecureBearSSL.h>
#include <ChatGPT.hpp>

static const char *ssid = "SSID";
static const char *password = "PASS";

BearSSL::WiFiClientSecure client;
ChatGPT<BearSSL::WiFiClientSecure> chat_gpt(&client, "v1", "KEY");


void setup() {
  Serial.begin(115200);
  Serial.println();
  Serial.print("Connecting to WiFi network: ");
  Serial.println(ssid);
  WiFi.begin(ssid, password);

  while (WiFi.status() != WL_CONNECTED) {
    Serial.print(".");
    delay(1000);
  }

  // Ignore SSL certificate validation
  client.setInsecure();
  Serial.println();
}


String rslt;
String inpt;


void loop() {
  Serial.println();
  Serial.println();
  Serial.println("Enter your question");
  while (!Serial.available()) delay(300);
  inpt=Serial.readString();
  inpt.trim();
  Serial.println(inpt);
  if (chat_gpt.simple_message("gpt-3.5-turbo-0301", "user", inpt, rslt)) {
    Serial.println("===OK===");
    Serial.println(rslt);
  } else {
    Serial.println("===ERROR===");
    Serial.println(rslt);
  }  
 delay(1000);
  
}
```

**Comment by 0015** [comment]
@ESPboy-edu It seems that heap memory is running out when parsing with ArduinoJSON on ESP8266.
It looks like you have to get the content string directly from the JSON string returned from the server without using ArduinoJSON. You can get the original string by using chat_gpt.full_message() instead of chat_gpt.simple_message(). Let me try a new way to save memory.

**Comment by ericTspel** [comment]
I'm also having this problem. When replaced with full.message I no longer get an error, but I still don't get any reply from ChatGPT

**Comment by 0015** [comment]
@ericTspel Which device are you using?

**Comment by ericTspel** [comment]
I'm using an adafruit feather huzzah

**Comment by ESPboy-edu** [comment]
the same problem on ESP8266

**Comment by 0015** [comment]
@ESPboy-edu adafruit feather huzzah is based on ESP8266. This is a problem with ESP8266.

**Comment by ESPboy-edu** [comment]
probably not enough memory for processing Json
