### ISSUE TITLE
Getitng Connection Fail Error

### ISSUE THREAD

**Issue by piyushy1** [0015/ChatGPT_Client_For_Arduino#5]
I am trying to run  sketch on Arduino Nano RP2040 Connect and getting 'Connection Faild Error'. 

`16:33:13.395 -> Connecting to Wi-Fi...Connecting to Wi-Fi...Connecting to Wi-Fi...Connecting to Wi-Fi...
16:35:51.138 -> Connected to Wi-Fi!
16:35:51.138 -> 
16:35:51.138 -> [ChatGPT] Only print a content message
16:35:51.404 -> ===ERROR===
16:35:51.404 -> [ERR] Connection failed!
`

Installed version 0.1.2
Sample Arduino Code 

```
#include <ArduinoJson.h>
#include <WiFiNINA.h>
#include <ArduinoBearSSL.h>
#include <ChatGPT.hpp>

static const char *ssid = "xxxx";
static const char *password = "xxx";

WiFiClient client;
BearSSLClient sslClient(client);
ChatGPT<BearSSLClient> chat_gpt(&sslClient, "v1", "xxxxxx");

void setup() {
  Serial.begin(115200);

  // Wait for serial port to initialize
  while (!Serial) {
    delay(10);
  }

  // Connect to Wi-Fi network
  connectWiFi();

  // Ignore SSL certificate validation
//  client.setInsecure();

  String result;
  Serial.println("[ChatGPT] Only print a content message");
  if (chat_gpt.simple_message("gpt-3.5-turbo-0301", "user", "Planning a 3-day trip to San Diego", result)) {
    Serial.println("===OK===");
    Serial.println(result);
  } else {
    Serial.println("===ERROR===");
    Serial.println(result);
  }
}

void loop() {}

void connectWiFi() {
  // Connect to Wi-Fi network
}
```
Any suggestions would be helpful.

**Comment by 0015** [comment]
@piyushy1 could you try it again with the insecure connection option? I believe your client has the option called, setInsecure or something similar.

**Comment by piyushy1** [comment]
Thanks. I was able to resolve the client issue via - https://reference.arduino.cc/reference/en/libraries/wifinina/wifisslclient/
