### ISSUE TITLE
azure-openai compatible with azure open ai api?

### ISSUE THREAD

**Issue by William-ywh** [0015/ChatGPT_Client_For_Arduino#7]
Hi! Thanks for ur excellent work in implementing this great library for arduino and esp32 interacting with chatgpt. i hv met a question right now since i hv another free subscription of azure openai api, i wonder if this kind of key is compatible with ur library to use?

**Comment by 0015** [comment]
@William-ywh I don't think so. For using Azure openai API, you need to look into ways to connect. Usually there is curl and you need to convert it to http format.

**Comment by William-ywh** [comment]
Thank you for ur prompt reply. i saw in ur example <espwifixxx> file that it has this code line: ChatGPT<WiFiClientSecure> chat_gpt(&client, "v1", "<OpenAI_API_KEY>"). i just wonder if i can just fill in azure openai api key into the <OpenAI_API_KEY>?

**Comment by William-ywh** [comment]
oh btw i hv one http link here for the azure api subscription: https://hkust.azure-api.net/openai/deployments/%7Bdeployment-id%7D/chat/completions?api-version=2023-05-15   i wonder if i hv this link then how can i use ur library?

**Comment by 0015** [comment]
Since the values returned from the API are different, this must be implemented accordingly.

**Comment by William-ywh** [comment]
OK no problem. Thank you very much and this problem i hv solved already.
